name: package app

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url --no-cache-dir https://download.pytorch.org/whl/cpu pyside6 ultralytics pyinstaller 

      - name: build with pyinstaller
        run: |
          pyinstaller main.py --name "Lucile" --windowed
            
      - name: package windows artifacts
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path dist/Lucile -DestinationPath Lucile-Windows.zip

      - name: package macOS artifacts
        if: runner.os == 'macOS'
        run: |
          zip -r Lucile-macOS.zip dist/Lucile.app

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ runner.os }}
          path: ./*.zip

  release:
    name: create gh release
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: download all artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: create release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
